import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  zephyrTrainingSidebar: [
    {type: 'autogenerated', dirName: 'zephyr-training'},
  ],

  zephyrNotesSidebar: [
    {
      type: 'category',
      label: 'Zephyr RTOS Notes',
      collapsible: false,
      items: [
        'zephyr/devicetree-primer',
        'zephyr/writing-a-driver',
      ],
    },
  ],

  protocolsSidebar: [
    {
      type: 'category',
      label: 'Protocols',
      collapsible: false,
      items: ['protocols/index'],
    },
  ],

  iiotSidebar: [
    {
      type: 'category',
      label: 'Industrial IoT',
      collapsible: false,
      items: ['industrial-iot/index'],
    },
  ],

  aiotSidebar: [
    {
      type: 'category',
      label: 'AIoT & Edge AI',
      collapsible: false,
      items: ['aiot/index'],
    },
  ],

  hardwareSidebar: [
    {
      type: 'category',
      label: 'Hardware',
      collapsible: false,
      items: ['hardware/index'],
    },
  ],

  referenceSidebar: [
    {
      type: 'category',
      label: 'Reference',
      collapsible: false,
      items: [
        'reference/tools',
      ],
    },
  ],
};

export default sidebars;
